### PR TITLE
97: Link math library with -lm

### LINKED ISSUE #97: Link math library by default
**Describe the bug**
Missing `-lm` linker flag fails to compile math functions on some platforms

### PR DESCRIPTION
**Pull request by JamesOrson**
Closes #97

### CODE REVIEW

File: src/include/generation/generate_c.h [hunk 1]
```diff
@@ -93,7 +93,6 @@ int generate_c_code(
 
 int generate_c_include_prelude(FILE* output_file) {
 	fputs("#include <assert.h>\n", output_file);
-	fputs("#include <math.h>\n", output_file);
```
Comment (JamesOrson) [inline src/include/generation/generate_c.h:96]: I do not want to include this by default, as I intend to write a math standard library for Daybreak very soon. If needed, this can now be imported with
```nim
importc "math.h"
```
